language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - "2.1.5"

gemfile:
  - gemfiles/redis_3_0_0.gemfile
  - gemfiles/redis_3_2_1.gemfile

script: bundle exec rake test_with_coveralls

services:
  - redis-server